//File Integrity Checker
#include <map>
#include <cstring>
#include <string>
#include <iostream>
#include <fstream>
#include <iomanip>
#include "TFile.h"
#include "TProfile.h"
#include "TH1.h"
#include "TH2.h"
#include "TProfile2D.h"
#include "TMath.h"
#include "TCanvas.h"
#include "TStyle.h"
#include <TSystem.h>
using namespace std;

int runnumber[10] = {326776, 326822, 326883, 326943, 327078, 327211, 327327, 327464, 327524, 327560};
int num_events[10] = {7003688, 554328, 1256669, 2915939, 4313507, 5989364, 7381724, 26153915, 3584837, 2969136}; //in runnumber order


void File_Integrity_Checker(bool Special_Cuts){
	string centralitystring[10];// used for both types of cuts

	string centralitystring_OG[10] = {"0-10%", "10-20%", "20-30%", "30-40%", "40-50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%"};
	string centralitystring_Special_Cuts[3] = {"10-60_10-20%", "5-40_10-20%", "5-80_10-20%"}; //used a code technicality to store the centrality data for non standard centrality units in the 10-20% bin
	int C = 0;
	int SysMax = 4;
	int VertMax = 3;

	if (Special_Cuts == true){
		for (int i = 0; i < 3; i++){
			centralitystring[i] = centralitystring_Special_Cuts[i];
		}
		C = 3;
		SysMax = 1;
		VertMax = 1;
	}
	if (Special_Cuts != true){
		for (int i = 0; i < 10; i++){
			centralitystring[i] = centralitystring_OG[i];
		}
		C = 9;
	}
		
	string Systematics[4] = {"Normal", "LOOSE", "NOMINAL", "TIGHT"};
	
	string Verticies[3] = {"Normal", "WIDE", "NARROW"};
	
	//FOR LOOP TO SHORTEN LINE LENGTH SO I CAN INPUT WHICH CENT AND RUN Number
	//this is utterly gargantuan and may be dififcult to read, this was designed this way for ease of use for the less code inclined.
	//keep in mind all this code does is the same thing but like 40 times
	int CentMax = 10;



	for (int c = 0; c < C; c++){ //cent bins
		for (int s = 0; s < SysMax; s++){//systematics
			if (s == 2){ continue;}
			for(int v = 0; v < VertMax; v++){//vertex
				cout << v << endl;
				//Even
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326776/ROOT/%s/%s/326776_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326776/ROOT/%s/%s/326776_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326822/ROOT/%s/%s/326822_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326822/ROOT/%s/%s/326822_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326883/ROOT/%s/%s/326883_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326883/ROOT/%s/%s/326883_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326943/ROOT/%s/%s/326943_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326943/ROOT/%s/%s/326943_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327078/ROOT/%s/%s/327078_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327078/ROOT/%s/%s/327078_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327211/ROOT/%s/%s/327211_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327211/ROOT/%s/%s/327211_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327327/ROOT/%s/%s/327327_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327327/ROOT/%s/%s/327327_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327464/ROOT/%s/%s/327464_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327464/ROOT/%s/%s/327464_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327524/ROOT/%s/%s/327524_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327524/ROOT/%s/%s/327524_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327560/ROOT/%s/%s/327560_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327560/ROOT/%s/%s/327560_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				//Odd
				

				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326776/ROOT/%s/%s/326776_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326776/ROOT/%s/%s/326776_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326822/ROOT/%s/%s/326822_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326822/ROOT/%s/%s/326822_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326883/ROOT/%s/%s/326883_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326883/ROOT/%s/%s/326883_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326943/ROOT/%s/%s/326943_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/326943/ROOT/%s/%s/326943_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327078/ROOT/%s/%s/327078_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327078/ROOT/%s/%s/327078_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327211/ROOT/%s/%s/327211_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327211/ROOT/%s/%s/327211_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327327/ROOT/%s/%s/327327_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327327/ROOT/%s/%s/327327_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327464/ROOT/%s/%s/327464_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327464/ROOT/%s/%s/327464_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327524/ROOT/%s/%s/327524_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327524/ROOT/%s/%s/327524_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327560/ROOT/%s/%s/327560_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_HF_RXN_Data_Sets/327560/ROOT/%s/%s/327560_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				//RPD RXN Plane Method
				//Even
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326776/ROOT/%s/%s/326776_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326776/ROOT/%s/%s/326776_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326822/ROOT/%s/%s/326822_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326822/ROOT/%s/%s/326822_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326883/ROOT/%s/%s/326883_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326883/ROOT/%s/%s/326883_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326943/ROOT/%s/%s/326943_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326943/ROOT/%s/%s/326943_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327078/ROOT/%s/%s/327078_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327078/ROOT/%s/%s/327078_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327211/ROOT/%s/%s/327211_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327211/ROOT/%s/%s/327211_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327327/ROOT/%s/%s/327327_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327327/ROOT/%s/%s/327327_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327464/ROOT/%s/%s/327464_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327464/ROOT/%s/%s/327464_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327524/ROOT/%s/%s/327524_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327524/ROOT/%s/%s/327524_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327560/ROOT/%s/%s/327560_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327560/ROOT/%s/%s/327560_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}

				//Odd
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326776/ROOT/%s/%s/326776_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326776/ROOT/%s/%s/326776_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326822/ROOT/%s/%s/326822_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326822/ROOT/%s/%s/326822_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326883/ROOT/%s/%s/326883_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326883/ROOT/%s/%s/326883_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326943/ROOT/%s/%s/326943_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/326943/ROOT/%s/%s/326943_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327078/ROOT/%s/%s/327078_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327078/ROOT/%s/%s/327078_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327211/ROOT/%s/%s/327211_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327211/ROOT/%s/%s/327211_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327327/ROOT/%s/%s/327327_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327327/ROOT/%s/%s/327327_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327464/ROOT/%s/%s/327464_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327464/ROOT/%s/%s/327464_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327524/ROOT/%s/%s/327524_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327524/ROOT/%s/%s/327524_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327560/ROOT/%s/%s/327560_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_RPD_RXN_Data_Sets/327560/ROOT/%s/%s/327560_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}

		
				//(B) Part B get the actual data from the loaded in plots using the "Get" command

				//HF  SPM Method
				//Even
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_HF_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}


				//Odd
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/HF/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_HF_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}


				//RPD SPM Method
				//Even
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_RPD_V1_Even_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}


				
				//Odd
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326776/ROOT/%s/%s/RunNumber_326776_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326822/ROOT/%s/%s/RunNumber_326822_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326883/ROOT/%s/%s/RunNumber_326883_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/326943/ROOT/%s/%s/RunNumber_326943_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327078/ROOT/%s/%s/RunNumber_327078_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327211/ROOT/%s/%s/RunNumber_327211_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327327/ROOT/%s/%s/RunNumber_327327_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327464/ROOT/%s/%s/RunNumber_327464_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327524/ROOT/%s/%s/RunNumber_327524_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
				if ((gSystem->AccessPathName(Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()), kFileExists )) == 1){ cout << "FILE " << Form("/data2/users/ebadams/Eric_SP_Data_Sets/RPD/327560/ROOT/%s/%s/RunNumber_327560_Sys_%s_Vtx_%s_RPD_V1_Odd_Histo_%s.root", Systematics[s].c_str(), Verticies[v].c_str(), Systematics[s].c_str(), Verticies[v].c_str(), centralitystring[c].c_str()) << " Does not exist" << endl;}
		
			
			
			
			
			
			
			
			
			
			



			}
		}
	}
}